# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m.xci
# IP: The module: 'clk_wiz_72m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_72m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_72m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_72m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m.xci
# IP: The module: 'clk_wiz_72m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_72m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_72m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_72m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
