# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config  -id {Labtoolstcl 44-513}  -string {{ERROR: [Labtoolstcl 44-513] HW Target shutdown. Closing target: localhost:3121/xilinx_tcf/Xilinx/000018ff1efa01}}  -suppress 
create_project -in_memory -part xc7a100tfgg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.cache/wt [current_project]
set_property parent.project_path C:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/new/uart_tx.v
  C:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/new/main_top.v
}
read_ip -quiet C:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m.xci
set_property used_in_implementation false [get_files -all c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m.xdc]
set_property used_in_implementation false [get_files -all c:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/sources_1/ip/clk_wiz_72m/clk_wiz_72m_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/constrs_1/new/LEDs.xdc
set_property used_in_implementation false [get_files C:/Users/chmun/Programming/Artix7/DDR_UART/DDR_UART.srcs/constrs_1/new/LEDs.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top led_top -part xc7a100tfgg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef led_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file led_top_utilization_synth.rpt -pb led_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
